#!/bin/bash

set -o errexit

[[ $( command -v xxhsum ) ]] || { echo error: xxhsum required; exit 1; }

path=

mkdir --parents /a/local/index
find /z/belimoth/data/data.subhelion.com -type f -print0 | xargs -0 xxhsum | sed "s|Z:/belimoth/data/data.subhelion.com/||" > /a/local/index/data.txt
code --diff /a/index/data.txt /a/local/index/data.txt
